"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$rust\
$golang\
$java\
$docker_context\
$line_break\
$character"""

[directory]
truncation_length = 3
truncation_symbol = ".../"

[git_branch]
format = "on [$branch]($style) "
style = "bold purple"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "bold red"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[python]
format = '[py $version]($style) '
style = "yellow"

[nodejs]
format = '[node $version]($style) '
style = "green"

[rust]
format = '[rs $version]($style) '
style = "red"

[golang]
format = '[go $version]($style) '
style = "cyan"

[java]
format = '[java $version]($style) '
style = "red"

[docker_context]
format = '[docker $context]($style) '
style = "blue"
